# Ground Segment
[example-service]
i2c_bus = "/dev/i2c-0"
i2c_addr = '0x03'
uart_bus = "/dev/ttyS0" #placeholder only
uart_timeout = '100'
udp_path = '127.0.0.1:8030'
udp_to = '127.0.0.1:8031'
err_buff_len = 64
wd_timeout = 1000
udp_socket = '0.0.0.0:8029' # listening to all network interfaces
target = '192.168.2.161:8029' # address of OBC on the network

# Space Segment
[example-service.addr]
ip = "0.0.0.0"
port = 8029

[example-service.comms]
max_num_handlers = 10
downlink_ports = [16002,8050,8080]
timeout = 1000
ip = "127.0.0.1"
